package rules

import com.my.model.Address;
import com.my.model.AddressCheckResult;

import function com.my.function.Foo.hello2
import function com.my.function.Utility.helper

import java.util.Date

declare Person1
    name : String 
    age : Integer 
    address : Address
end

declare Student
    firstName : String @key
    lastName : String @key
    age : int
end

rule "Using a declare"
lock-on-active
    when
       person: Person1(name == "Bob")
    then
    	// rule类可以在rule中使用
        Person1 mark = new Person1();
        // @key的使用
        Student stu = new Student("张","san",23);
        // Java类可以在rule中使用
        Address add = new Address();
        add.setStreet("qilinglu");
        mark.setName("Mark");
        System.out.println(hello2("Using a declare"));
        System.out.println(hello2(mark.getName()));
        System.out.println(hello2(stu.getFirstName()));
        System.out.println(hello2(add.getStreet()));
        helper(drools);
end

